version: '3'
services:
  redis:
    container_name: redis
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
  user:
    build:
      context: ./Services/UserService
      dockerfile: Dockerfile
    image: userservice:1.0
    container_name: userservice_V1
    ports: 
      - 5001:5001
    volumes:
    - ./Services/UserService:/app
    environment:
      MONGODB_ADMIN_NAME: root
      MONGODB_ADMIN_PWD: root
    depends_on:
      - user-db
    command: [sh, -c, npm install && npm uninstall bcrypt && npm install bcrypt && npm start]
  user-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  feed:
    build:
      context: ./Services/FeedService
      dockerfile: Dockerfile
    image: feedservice:1.0
    container_name: feedservice_V1
    ports: 
      - 5000:5000
    volumes:
    - ./Services/FeedService:/app
    environment:
      MONGODB_ADMIN_NAME: root
      MONGODB_ADMIN_PWD: root
    depends_on:
      - feed-db
    command: [sh, -c, npm install && npm start]
  feed-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
volumes:
  user-db:
  feed-db:


